name: flutter_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at 
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.6.9
  dartz: ^0.9.2
  dio: ^3.0.10
  flare_flutter: ^2.0.6
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  injectable: ^1.0.5
  kt_dart: ^0.8.0
  pin_code_fields: ^6.0.1
  provider: ^4.3.2+2
  retrofit: ^1.3.4
  shared_preferences: ^0.5.12+4
  uuid: ^2.2.2
  stomp_dart_client: ^0.3.7
  http: ^0.12.2
  permission_handler: ^5.0.1+1
  event_bus: ^1.0.1
  synchronized: ^2.1.0
  image_picker: ^0.6.7+12
  fluro: ^1.5.1
  fluttertoast: ^7.1.1
  keyboard_visibility: ^0.5.6
  path_provider: ^1.6.22
  audioplayers: ^0.14.0
  flutter_easyrefresh: ^2.1.6
  flutter_spinkit: ^4.1.2+1
  gzx_dropdown_menu: ^2.1.0
  im_stepper: ^0.1.2+8 
  date_time_picker: ^1.1.0
  image_gallery_saver: ^1.6.1
  cached_network_image: ^2.3.3
  share: ^0.6.5+4
  photo: ^0.4.8
  photo_view: ^0.10.3
  bot_toast: ^3.0.5
  jpush_flutter: ^0.6.2
  url_launcher: ^5.7.10
  rxdart: ^0.24.0
  flutter_app_badger: ^1.1.2
  flutter_audio_recorder: ^0.5.5
  pull_to_refresh: ^1.6.3
  flutter_image_compress: ^0.7.0
  flutter_swiper: ^1.1.6
  package_info: ^0.4.3
  ota_update: ^2.4.1
  flutter_echarts: ^1.5.0
  fl_chart: ^0.12.3
  flutter_rating_bar: ^3.2.0
  flutter_staggered_grid_view: ^0.3.4
  # amap_flutter_location: ^1.0.0
  marquee_flutter: ^0.1.4
  flutter_html: ^1.1.0
  # amap_flutter_map: ^1.0.0
  amap_map_fluttify: ^0.30.1
  amap_search_fluttify: ^0.16.2
  amap_location_fluttify: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_plugin_record:
  #   git:
  #     url: https://github.com/yxwandroid/flutter_plugin_record.git  
  flutter_record_plugin:
    git:
      url: https://github.com/huangruiLearn/flutter_record_plugin.git
      ref: ca5a0f3821616d38842dde4a6588a1ce9ad5673d
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.4
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  retrofit_generator: ^1.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec  
# The following section is specific to Flutter.  
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/pin_code/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# https://github.com/rrousselGit/freezed/issues/293
dependency_overrides:
  analyzer: '0.40.4'
